### ISSUE TITLE
Seismic regularization using PyLops GPU

### ISSUE THREAD

**Issue by AlejaHernandezRojas** [equinor/pylops-gpu#15]
Hello!
I am interested in doing an example of seismic regularization using PyLops GPU and wavelet transform. However, when I create the restriction operator using 'pylops_gpu.Restriction' and multiply it by an array that represents my seismic image, I got an error: "Restriction currently works only on 1d arrays". I share my Colab showing the exercise using only PyLops and later using PyLops GPU, and the error that I got: https://colab.research.google.com/drive/19rk-8w0vWKg9UDHJfcG3lEYJwdRJchHM#scrollTo=k_Hix45Dl5cj 

Additionally, I would like to know if it is possible to create the wavelet transform using PyLops GPU.

Thank you so much!

**Comment by mrava87** [comment]
Hi,
thanks for your issue.

I do not have access to your Colab notebook, I asked for it.

To your questions:

- No, unfortunately Restriction in pylops-gpu does not yet support broadcasting. You could still do what you want, if you simply provide all the indices you want to sample from the flattened image.
- No, the wavelet transform that we use in PyLops is CPU only from PyWavelets. I am not aware of any GPU based implementation available in Python so you would need to write it yourself ;) 

However, I would like to ask why you want to use pylops-gpu as this is a fairly immature library which we don't plan to develop further as we found better solutions to the needs of performing matrix-free optimization on GPUs. If you only care about doing your inversion on a GPU, PyLops has now a full integration with cupy, see here for some examples https://github.com/PyLops/pylops_notebooks/tree/master/developement-cuda

If instead you want to integrate PyLops operators with Pytorch (eg mix them with native Pytorch Deep learning operators like Fully-connected network blocks, or conv blocks), we have created a wrapper operator called TorchOperator that allows you to that using PyLops operators. An example is here https://github.com/PyLops/pylops_notebooks/blob/master/developement-cuda/PyTorch_Lopextension_cupy.ipynb
